INSERT INTO SERVICE_POOL (ID, AVAILABLE_FLAG) values('1','Y');
INSERT INTO SERVICE_POOL (ID, AVAILABLE_FLAG) values('2','Y');
INSERT INTO SERVICE_POOL (ID, AVAILABLE_FLAG) values('3','Y');
INSERT INTO SERVICE_POOL (ID, AVAILABLE_FLAG) values('4','Y');
INSERT INTO SERVICE_POOL (ID, AVAILABLE_FLAG) values('5','Y');
